### PR TITLE
Add android standalone toolchain script to build script

### PR DESCRIPTION
**Pull request by vyrnix9582046173**
It might be easier to have people make their own standalone toolchains instead of extracting for the different hosts. Based off of node's android configure script https://github.com/nodejs/node/blob/master/android-configure#L41-L60

### CODE REVIEW

**Comment by ngokevin** [comment]
Would it be easier at the moment to not have to set up an NDK and build own toolchains? Right now, the toolchain ZIPs are there, only two hosts, and is just installed as part of npm.

**Comment by avaer** [comment]
BTW for magic leap we just take in the env var for the toolchain the user is expected to install.

But I think whatever else is fine, including `android-toolchain`, as long as toolchain binaries aren't checked in to the main repo.

**Comment by ngokevin** [comment]
Yeah, just sourced from GitHub via npm, not checked in.

**Comment by vyrnix9582046173** [comment]
Let's use `android-toolchain` for now.

**Pull request closed without merging**
